// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230713105409_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrate.Anket", b =>
                {
                    b.Property<int>("AnketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnketID"));

                    b.Property<string>("cevap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cevap9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soru")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnketID");

                    b.ToTable("ankets");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Dosya", b =>
                {
                    b.Property<int>("DosyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DosyaID"));

                    b.Property<string>("Akissemasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("basvuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("degerledirmedok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("degerlendirmeform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raporsablon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yonerge")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DosyaID");

                    b.HasIndex("StudentID");

                    b.ToTable("dosyas");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Personal", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("personals");
                });

            modelBuilder.Entity("EntityLayer.Concrate.StajBilgi", b =>
                {
                    b.Property<int>("StajBilgiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StajBilgiID"));

                    b.Property<string>("AdUnvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alanı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Başlamatrh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Bitistrh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CmtDahil")
                        .HasColumnType("bit");

                    b.Property<bool>("Egitim")
                        .HasColumnType("bit");

                    b.Property<string>("FaksNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Kabul")
                        .HasColumnType("bit");

                    b.Property<int>("KabulGün")
                        .HasColumnType("int");

                    b.Property<bool>("KatkıPayıOnay")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Onay")
                        .HasColumnType("bit");

                    b.Property<string>("RedSebep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ResmiTatil")
                        .HasColumnType("bit");

                    b.Property<string>("StajTürü")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stajsayi")
                        .HasColumnType("int");

                    b.HasKey("StajBilgiID");

                    b.HasIndex("StudentID")
                        .IsUnique();

                    b.ToTable("stajBilgis");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Student", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sınıf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("students");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Dosya", b =>
                {
                    b.HasOne("EntityLayer.Concrate.Student", "student")
                        .WithMany()
                        .HasForeignKey("StudentID");

                    b.Navigation("student");
                });

            modelBuilder.Entity("EntityLayer.Concrate.StajBilgi", b =>
                {
                    b.HasOne("EntityLayer.Concrate.Student", "student")
                        .WithOne("StajBilgis")
                        .HasForeignKey("EntityLayer.Concrate.StajBilgi", "StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Student", b =>
                {
                    b.Navigation("StajBilgis")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
